name: Lint

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2

        - name: Super-Linter
          uses: github/super-linter@v4

        - name: Bandit
          run: |
            pip3 install bandit
            bandit --skip B101,B310,B404,B603,B607 --recursive .
